const INIT_APP = 'INIT_APP'
const UPDATE_DATA = 'UPDATE_DATA'
const UPDATE_THEME = 'UPDATE_THEME'
const UPDATE_EDITOR = 'UPDATE_EDITOR'
const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM'
const UPDATE_MENU_VAL = 'UPDATE_MENU_VAL'

export default {
  INIT_APP,
  UPDATE_DATA,
  UPDATE_THEME,
  UPDATE_EDITOR,
  UPDATE_MENU_ITEM,
  UPDATE_MENU_VAL
}