const INIT_APP = 'INIT_APP'
const UPDATE_DATA = 'UPDATE_DATA'
const UPDATE_THEME = 'UPDATE_THEME'
const UPDATE_EDITOR = 'UPDATE_EDITOR'

export default {
  INIT_APP,
  UPDATE_DATA,
  UPDATE_THEME,
  UPDATE_EDITOR
}